import { test, expect } from '@playwright/test';

// Security regression test — generated by VibeAudit
// Ensures BOLA vulnerability on /api/profile/cmpjx814a0000i40xodaftkbs stays fixed
// If this test fails, the authorization check has been removed
//
// Sensitive fields that must NOT be exposed to non-owners:
//   - creditCard (FINANCIAL)
//   - bankAccount (FINANCIAL)
//   - ssn (PII)
//   - address (PII)
//   - phone (PII)

test.describe('BOLA Regression: /api/profile/cmpjx814a0000i40xodaftkbs', () => {
  test('attacker cannot access victim record cmpjx814a0000i40xodaftkbs', async ({ request }) => {
    // Step 1: Authenticate as attacker (User B)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: 'attacker@shopvuln.com',
        password: 'password123',
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Attempt to access victim's record using attacker session
    const attackRes = await request.get('/api/profile/cmpjx814a0000i40xodaftkbs', {
      headers: { Cookie: cookies },
    });

    // Step 3: Must return 403 Forbidden — not 200
    expect(attackRes.status()).toBe(403);

    // Step 4: Response body must not contain victim's sensitive data
    const body = await attackRes.json().catch(() => ({}));
    expect(body.creditCard).toBeUndefined();
    expect(body.bankAccount).toBeUndefined();
    expect(body.ssn).toBeUndefined();
    expect(body.address).toBeUndefined();
    expect(body.phone).toBeUndefined();
  });

  test('owner can still access their own record', async ({ request }) => {
    // Step 1: Authenticate as victim (record owner)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: 'victim@shopvuln.com',
        password: 'password123',
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Access own record
    const res = await request.get('/api/profile/cmpjx814a0000i40xodaftkbs', {
      headers: { Cookie: cookies },
    });

    // Step 3: Owner should still get 200
    expect(res.status()).toBe(200);
  });
});
