import { test, expect } from '@playwright/test';

// Security regression test — generated by VibeAudit
// Ensures BOLA vulnerability on /api/records/REC-10041 stays fixed
// If this test fails, the authorization check has been removed

test.describe('BOLA Regression: /api/records/REC-10041', () => {
  test('attacker cannot access victim record REC-10041', async ({ request }) => {
    // Step 1: Authenticate as attacker (User B)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: 'attacker@meditrack.app',
        password: 'attacker123',
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Attempt to access victim's record using attacker session
    const attackRes = await request.get('/api/records/REC-10041', {
      headers: { Cookie: cookies },
    });

    // Step 3: Must return 403 Forbidden — not 200
    expect(attackRes.status()).toBe(403);

    // Step 4: Response body must not contain victim's sensitive data
    const body = await attackRes.json().catch(() => ({}));
    expect(body.fullName).toBeUndefined();
    expect(body.diagnosis).toBeUndefined();
    expect(body.prescription).toBeUndefined();
  });

  test('owner can still access their own record', async ({ request }) => {
    // Step 1: Authenticate as victim (record owner)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: 'james@meditrack.app',
        password: 'patient123',
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Access own record
    const res = await request.get('/api/records/REC-10041', {
      headers: { Cookie: cookies },
    });

    // Step 3: Owner should still get 200
    expect(res.status()).toBe(200);
  });
});
